### ISSUE TITLE
PHELI

### ISSUE THREAD

**Issue by OpheliaDeutschland** [forkdelta/tokenbase#1183] opened 2018-05-29 14:59 UTC
Hi forkdelta, 
We request the listing of our Token Ophelia Pheli " PHELI ".
 
Token Adress: https://etherscan.io/token/0x4df42d7317561f1540934f17c9aac68d6a21024e
Official Website: https://www.opheliapheli.com/ 

What is Ophelia Pheli PHELI about? The "PHELI" platform will allow anyone to provide services and sell second-hand goods for payment in bitcoin or other cryptocurrencys. Based on the "PHELI" platform we will develop a possibility how employees can be paid legally compliant in Bitcoin or possibly other crypto currencies. We will develop a software, possibly also hardware, which will enable this process to be both easy and controlled for the employer and, on the other hand, that payment can be carried out correctly in terms of legal requirements. We can imagine this as a digital cash register, which on the one hand enables remuneration and allows cooperation with the state authorities.

Contract Adress Confirmation: Click on the Pheli Logo at the end of the homepage or have a look at the lightpaper. 

Bitcointalk Thread: https://bitcointalk.org/index.php?topic=3173897.0 

Thank you very much.

**Comment by freeatnet** [comment] 2018-06-06 12:47
Duplicate of #1183. If you would like to update or include additional information, please post it in #1183.

**Closed by freeatnet** 2018-06-06 12:47 UTC
