### ISSUE TITLE
(ADN) ADN Listing

### ISSUE THREAD

**Issue by TOKTOKnet** [forkdelta/tokenbase#1157] opened 2018-05-25 11:12 UTC
ToktokICO is certification for token listing

Contract address: 0x6e8e46ec6635ad21be4fdf1412ac4bde8e7bf39c

erc20 on official website: http://adn-project.org/erc20

Official contract address confirmation: https://bitcointalk.org/index.php?topic=3193462

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3193462

Description : ADN is a cryptocurrency that opens the oppotunity to mining by smartphone.
ADN is fully decentralized and open to all. Anyone can take part in the forefront and mine ADN from his smartphone.

**Comment by freeatnet** [comment] 2018-06-06 12:39
Duplicate of #825.

**Closed by freeatnet** 2018-06-06 12:39 UTC
