### ISSUE TITLE
ndex coin listing

### ISSUE THREAD

**Issue by psbalaji777** [forkdelta/tokenbase#1787] opened 2018-10-02 01:29 UTC
**Token address:** 0x1966d718A565566e8E202792658D7b5Ff4ECe469

**Issuer's official website:**https://ndexnetwork.com/

**Description:** nDEX Network is a blockchain business development start up that that seeks to provide for the entire blockchain 
community, robust exchange platforms both centralized and decentralized to give the community
a mixed sensation of both centralized and decentralized trading experience while at the same time 
providing a fun-enabled platform where users get to showcase their gaming skills and catch immense fun. 
nDEX Network's 3 ongoing and finished projects are: nDEX Market, BlockRoll and nEXBit.

**A link to the official contract address confirmation:** https://ndexnetwork.com/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://ndex.market/
https://bitcointalk.org/index.php?topic=4479873.new#new
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
-->
1. https://www.facebook.com/ndexnetwork
2.https://twitter.com/NdexOfficial
3.https://bitcointalk.org/index.php?topic=4479873.new#new
4.https://github.com/ndexnetwork
5.https://medium.com/@nDEXofficial
6.https://t.me/ndexofficial

**Comment by freeatnet** [comment] 2018-10-02 10:52
Duplicate of #1786. If you have additional information that you believe is missing from the request, please add it as a comment to #1786.

**Closed by freeatnet** 2018-10-02 10:52 UTC
Labels: duplicate
