### ISSUE TITLE
Please list CHT - Countinghouse Fund

### ISSUE THREAD

**Issue by bswatkins** [forkdelta/tokenbase#1592] opened 2018-08-20 19:25 UTC
Please list Countinghouse CHT tokens on Forkdelta
Note that this token has been trading on Forkdelta with reasonable volume for over two months already.  I just want to have the CHT token name added to your official list.

Contract address:
0x799d214d7143B766cDd4979cd0280939288ba931

1-3 sentences for the token's description:
Countinghouse Fund is a direct-hedging fund that uses trading algorithms and mathematical techniques to force profit from market volatility and movement, in both bull and bear markets. 
The role of the token is to represent a share of the fund's underlying total liquid value, which is intended to grow over time following successful trading outcomes.

A link to an official page confirming the above contract address:
https://www.countinghousefund.com/single-post/2018/03/30/How-to-buy-our-tokens

Links to third-party reviews or discussion of the token:
https://icorating.com/ico/countinghouse-cht/
https://medium.com/@neurosurgeonkosei/countinghouse-the-relevance-of-cht-token-on-the-platform-5b6073194c20
https://coinscribble.com/why-you-need-to-buy-countinghouse-cht-now-even-in-this-crypto-winter/1426/opinion/37/
https://www.cryptocompare.com/coins/cht/overview/BTC
https://t.me/Countinghouse
https://t.me/countinghouseico

**Comment by bswatkins** [comment] 2018-08-20 20:00
Ok, I see someone else has already opened this issue. Hopefully the extra detail I've provided assists in the decision making,

**Comment by freeatnet** [comment] 2018-09-13 09:30
Closing as a duplicate of #1575. If you have additional information, please post it in the original request. Thanks!

**Closed by freeatnet** 2018-09-13 09:30 UTC
