### ISSUE TITLE
CargoCoin listing

### ISSUE THREAD

**Issue by thecargocoin** [forkdelta/tokenbase#1159] opened 2018-05-25 15:46 UTC
We would like to add CargoCoin to Forkdelta exchange. Here's the information of our token:
Contract address: 0xf49cdd50ad408d387d611f88a647179c3de3492b
Name: CargoCoin (Ticker: CRGO)
Website: https://thecargocoin.com
Official contract address confirmation: https://thecargocoin.com/index.html
Links to official reviews:
https://irishtechnews.ie/business-showcase-cargocoin/
http://ftreporter.com/cargocoin-the-shipping-industry-game-changer/
https://cryptocoin.news/icos/cargocoin-ico-review-decentralized-blockchain-platform-smart-contract-to-optimize-the-transport-industry-worldwide-10170/
https://cryptocentral.io/blockchain-solution-for-the-global-transport-industry/
https://irishtechnews.ie/using-the-blockchain-to-transform-cargo-transport-martin-iliev-cargocoin/
https://www.coinstaker.com/blockchain-solution-for-the-global-transport-industry/

**Comment by freeatnet** [comment] 2018-06-06 12:52
Duplicate of #1097. If you have additional information or wish to update the request, please use #1097.

**Closed by freeatnet** 2018-06-06 12:52 UTC
