### ISSUE TITLE
Add PlusCoin (PLCN) Token (PlusCoin Fork)

### ISSUE THREAD

**Issue by arkadiyo** [forkdelta/tokenbase#1428] opened 2018-07-11 16:29 UTC
Token address: 0xcfc2437916a6df165235272dbfb116687bb1a00b

Issuer's official website: https://pluscoin.io/

Description: DS PLUS is a crypto cashback service for its users and a CPA platform for businesses in the whole world. It is based on a mobile app. PlusCoin is a cryptocurrency integrated in the mobile app and other DS PLUS platforms.

A link to the official contract address confirmation: https://pluscoin.io/ (PLCN contract address: 0xcfc2437916A6df165235272dbfb116687bb1A00b)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://cryptellect.net/plcn-fork-tokena-pluscoin-vnutrennej-valyuty-platformy-ds-plus/
https://coinidol.com/blockchain-technology-in-marketing-pluscoin-introduce-crypto-cashback/

**Comment by freeatnet** [comment] 2018-07-12 09:05
Thank you for your request, @arkadiyo! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment] 2018-07-12 09:33
Duplicate of #1406, #1272.

**Comment by freeatnet** [comment] 2018-09-25 21:10
Resolved in #1726

**Closed by freeatnet** 2018-09-25 21:10 UTC
Labels: duplicate, medium
