### ISSUE TITLE
New token listing application - Bityuan

### ISSUE THREAD

**Issue by OurnadHuan** [forkdelta/tokenbase#1199] opened 2018-06-01 06:23 UTC
Hi ForkDelta team,

We are from Bityuan team. Bityuan is a self-developed public blockchain network, it can be used to paying, receiving and storing various cryptocurrencies, it also supports 'wallet recovery', C2C trading, atomic cross-chain trading and parallel blockchain and some other functionalities.

The main network is just released a couple of weeks ago, independent wallet and blockchain explorer can be viewed on the official website: www.bityuan.com. You can also read the white paper on it. I hope we could get in touch, I would love to tell you more about the project and what we can do.

Best regards,
Bityuan team

**Comment by freeatnet** [comment] 2018-06-06 18:08
Thank you for your request, @OurnadHuan! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment] 2018-06-06 18:16
Is this a duplicate of #1149?

**Comment by freeatnet** [comment] 2018-06-13 10:12
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Closed** 2018-07-04 20:14 UTC
Labels: missing information
