### ISSUE TITLE
Add PlusCoin (PLCN) new

### ISSUE THREAD

**Issue by robertfordsilva** [forkdelta/tokenbase#1406] opened 2018-07-07 10:46 UTC
Good Morning Sir,

introduction about the project for us?

DS PLUS - A Decentralized Cashback Platform on the Ethereum Blockchain.
PLUSCOIN - A tool for marketing offline and online organizations and attracting new players and consumers into the blockchain.
We are the cashback service for users and the lead generator for the on-line and off-line business in Russia and abroad based on the DS Plus mobile application. We use the blockchain technology to control transactions and to provide a safety payment of your purchases for PlusCoin cryptocurrency integrated in the application. There are two main objectives of our project: to popularize blockcain technologies and to embed the cryptocurrency, which was made for people, into our everyday life.

Is your token listed on the other exchanges?
-DDEX
- TIDEX (https://tidex.com/exchange/plc/eth)
- Tokenjar

Your "non-security token" legal documentation 

The document will be attached in the next message

Your smart contract basic info (symbol+token address+decimal

PlusCoin
New
PLCN 0xcfc2437916A6df165235272dbfb116687bb1A00b
decimal - 18

Your Project Logo in AI file for our designer to edit

The Project Logo will be attached in the next message

 Visit our official website for more information:

https://pluscoin.io

Official forums:
https://www.reddit.com/r/PlusCoin/
https://bitcointalk.org/index.php?topic=2067375.0
https://medium.com/@DSPlus.io
https://t.me/PlusCoinENG
https://t.me/Dsplusforkeng

 Social:
https://mobile.twitter.com/DsplusF
https://www.facebook.com/DS-PLUS-Fork-128078354505520/

**Comment by freeatnet** [comment] 2018-07-12 08:47
Thank you for your request, @robertfordsilva ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate.** This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by robertfordsilva** [comment] 2018-07-12 09:08
Hello sir, thank you for your message I should have sent you all the
requested information, if you wish I can also forward you the legal
contract via email.

Il Gio 12 Lug 2018 10:47 Arseniy Ivanov <notifications@github.com> ha
scritto:

**Comment by bobbypaintsstuf** [comment] 2018-07-16 21:32
@freeatnet  this is the new PLC listing

**Comment by bobbypaintsstuf** [comment] 2018-07-16 21:33
the following is a copy of their telegram pinned message it reads that all coins purchased after 10 may 2018 will not be elligable for the swap to the PLCN

🚀 Welcome to PLUS COIN NEW (PLCN)
 
➖ You can buy and sell PLCNs at the following addresses:

✔ ETHERDELTA
https://etherdelta.com/#0xcfc2437916a6df165235272dbfb116687bb1a00b-ETH
✔ FORKDELTA
https://forkdelta.github.io/#!/trade/0xcfc2437916a6df165235272dbfb116687bb1a00b-ETH
✔ TOKENJAR
https://tokenjar.io/

➖ NEW EXCHANGES WILL BE AVAILABLE

➖ Visit our official website for more information:

✔ https://pluscoin.io

➖ Official forums:
✔ https://www.reddit.com/r/PlusCoin/
✔ https://bitcointalk.org/index.php?topic=2067375.0
✔ https://medium.com/@DSPlus.io

➖ Social:
✔ https://mobile.twitter.com/DsplusF
✔ https://www.facebook.com/DS-PLUS-Fork-128078354505520/

❓ INFORMATION PLC ➡  PLCN SWAP

Send PLC to the address presented for the PLC exchange ➡  PLCN:

✔✔  0xEf2956FF9E796C956fb32DEF0F2dA069EeC4f7B6

❗ An exchange will be made once your application is reviewed by a moderator. In case you have purchased the tokens after 10 May 2018 it will not be possible to exchange them with PLCN.
The following terms of exchange are valid for those who maintain their PLC on EtherDelta, Forkdelta, Idex:

1. Send tokens to MyEtherWallet.

2. Open the instructions on the official website
(https://pluscoin.io) and copy the address must be used to commit a transaction in PLC.

3. Make a PLC transaction from MEW.

4. Open the Customer Portal (Customer Portal) and send a message containing the transaction link and a confirmation that the tokens were purchased before 10 May 2018 (screens, links for purchase transactions, etc.).

5. A moderator considers your application and makes a resolution.

6. In the event that all terms are met, you will receive PLCN.


✔ The opportunity to send large quantities of PLCs for exchange by PLCN is opened.
How does this function work?
1. For example, 20,000,000 PLCs are sent.
2. Once a week you will receive 7,000,000 PLCNs, and so on each week until complete exchange commitments are complete.

❗❗  CAUTION
❗❗  

➖  For any questions, leave an application on the Customer Portal

✔ https://dsplus.atlassian.net/servicedesk/customer/portal/

❌ CAUTION ... DO NOT MAKE SCAM. FAITH ONLY THE INFORMATION REPORTED BY TEAM MEMBERS, DO NOT SEND PLCs TO OTHER ADDRESSES.❌

**Comment by bobbypaintsstuf** [comment] 2018-07-16 21:39
when i asked via their customer portal i got this which seems to tie the 2 concepts of the cut off date and having coins on exchanges which could be confused to mean any coins purchased after 10 may from an exchange is still good in my interpritation of its meaning 

Reply above this line. 
Kristina Galkina commented:
1. We can not remove the trading pairs of PLC from the Etherdelta and Forkdelta exchanges, as these are decentralized exchanges and people who want to sell the PLC should somewhere to do it.
2. We made many warnings that you do not need to buy coins after May 10, 2018. Each investor must monitor the coins he wants to buy - these are the standards of any competent investments.
3. If you own a coin PLC, which is on IDEX (even if you bought it after May 10, 2018) you can get an exchange for a new coin PLCN. You will need to use the instruction:
1) Send PLC to the presented address:
0xEf2956FF9E796C956fb32DEF0F2dA069EeC4f7B6
2) Open the Customer Portal (Customer Portal) and send a message including the transaction link 
 
Kristina Galkina changed the status to Resolved.
 
Kristina Galkina resolved this as Done.

How was our service for this request?

**Comment by bobbypaintsstuf** [comment] 2018-07-16 22:53
https://github.com/robertfordsilva     https://github.com/KristinaPlusCoin  
     https://github.com/arkadiyo       https://github.com/freeatnet


i thought it only fair to copy you all into this as i have posted some comments above

**Comment by freeatnet** [comment] 2018-07-17 11:45
@bobbypaintsstuf Thank you for clarifying this. This will now be treated as an update situation.

**Comment by bobbypaintsstuf** [comment] 2018-07-17 12:50
@freeatnet you are welcome - https://github.com/KristinaPlusCoin says she will reply to this thread today clarifying all the questions

**Comment by KristinaPlusCoin** [comment] 2018-07-17 17:06
Answer №1. Yes, if somebody will buy PLC today or tomorrow, he will not be able to exchange them for PLCN. It is explained in the article: https://medium.com/@DsplusF/fork-pluscoin-the-launch-of-anti-crisis-measures-pluscoinnew-e824e426bd5f

Then on May 8, 2018 the team posted an advertisement in all media:

IMPORTANT

From 09/05/2018 from 12:00 PM all movements on the PLC are strongly recommended to be suspended, since for transactions made after this period, the exchange for PLCN will not function. This is done in order to prevent provocateurs and aggressors from bringing their coins to the market. No exceptions. For nobody.

Later the time limit was extended until May 10, 2018.

Why is it possible to exchange PLC, which people bought after May 10, 2018 on the IDEX exchange? Because trading on the coin were closed 2 weeks after the announcement about the FORK. We do not have direct contact with this exchange and wrote them a request using the support service on their official website. They received it, processed it and stopped trading. Another example is the TIDEX exchange, we have direct contact with them and we arranged about closing trading, entering and withdrawing PLC. We transferred an equal amount in PLCN to the exchange and they automatically assessed the PLC coins on TIDEX accounts to all who kept coins. We could not do the similar with the IDEX exchange, so we decided to exchange coins for anyone who still has coins on IDEX accounts.

For Etherdelta and Forkdelta exchanges, these conditions are not possible, because these are decentralized exchanges. Even if we requested removal of the PLC ticker, trading would continue using the smart contract address and the coin designation (see the section "Other tokens" on the exchanges). This would not change the situation in any way. We also need to take into account that we do not have the right to close trading completely, as the coin in any case exists, it can be traded, but it will not be able to function in the infrastructure of the DS PLUS (PlusCoin) project.

2. Answer №2. Yes, we understand that it is an important change, but I repeat that even if we removed the PLC ticker, people could still trade a coin using the smart contract address (see Other tokens on the exchange).

3. Answer №3. Because the company Zhilstroyleasing, which was mentioned in the article in the answer №1, began to sell coins that it did not own at almost zero rate to destroy the project. We should have act and we warned all our tokenholders that they should not buy coins from the Zhilstroyleasing company. We placed an ad several times, so that everyone saw it. It seems to me that every investor before buying coins should look through the latest news of the project and only after that buy coins.

4. Answer №4. I wrote the first request to ForkDelta. After that another request was written by a member of our team, Robert. And another request was sent from the official PlusCoin account, so that the exchange team realized that the appeal comes from the developer. We apologize for having created three requests; we did not want to look like spam in your eyes. And we apologize that we did not notify the exchange about May 10, 2018, but only because we thought that if the exchange was decentralized, it would still be impossible to do something with coins on users' accounts. And users could still trade PLC using the smart contract of the coin. If you think that it is necessary, you can remove the PLC ticker from the ForkDelta exchange. We will not object this process.

https://github.com/bobbypaintsstuf

**Comment by bobbypaintsstuf** [comment] 2018-07-17 22:33
Thank you for your reply. that all reads clearly now. To clarify for you and your team. tokens in FD come in two categories - 

category 1 - supported - coins are available in the pull down menu for easy locating by users and support is given to these coins by the FD team.

category 2 - non supported - these are traded purely on the smart contract - users do so at their own risk.


Therefore -
1)  FD can remove the token from the UI
2) FD can clear / close the order book - systems using FD data wont be effected, this will not effect EtherDelta.
3) This will not effect trades on the contract level as FD does not have ownership of the contract.

for future reference. PLC is a category 1 listing ( although it was an inherited listing from the delta's fork) and as such FD has an expectation in all circumstances to be informed in a timely and as far as possible in advance through official channels ( GitHub  issues ) of any changes to any coin in category 1, both now and in the future in order that FD can continue to provide  support to both teams and users

https://github.com/KristinaPlusCoin      https://github.com/robertfordsilva    https://github.com/arkadiyo
@freeatnet

**Comment by KristinaPlusCoin** [comment] 2018-07-18 11:49
Thank you for clarifying the information. We hope that the Forkdelta exchange will be able to give PLCN a trade ticker replacing PLC.

**Comment by bobbypaintsstuf** [comment] 2018-07-18 12:13
@freeatnet  - so the PLC is dead for trading and not eligible for the swap after the cut off date 10 may 2018 which has passed - seems they intended no harm just a lack of foresight in not informing FD due to their lack of understanding of FD's needs in this regard.
i think fair to say we should stop the order book on PLC and then update to PLCN if your happy to do so.

**Comment by bobbypaintsstuf** [comment] 2018-07-20 08:11
any additional info is always welcome.

**Comment by freeatnet** [comment] 2018-07-22 14:12
0xcfc2437916A6df165235272dbfb116687bb1A00b is confirmed on the [known official website](https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0x0835ecd15ddf08d4786304d71b4672dc5c40f011.yaml) of PLC (0x0835ecd15ddf08d4786304d71b4672dc5c40f011).

Resolution: assign PLC_OLD to 0x0835ecd15ddf08d4786304d71b4672dc5c40f011; assign PLCN to 0xcfc2437916A6df165235272dbfb116687bb1A00b.

**Comment by robertfordsilva** [comment] 2018-07-22 17:16
correct sir, if  you want other information, I am at your disposal, best regards @freeatnet

**Comment by KristinaPlusCoin** [comment] 2018-07-25 08:15
@freeatnet Thank you for approving the application. We hope that the PLCN coin will be listed until July 30, 2018, in time for the opening of testing of our P2P platform.

**Comment by KristinaPlusCoin** [comment] 2018-07-30 04:08
Good afternoon! I wanted to clarify when the PLC coin was replaced with a PLCN coin? We would like to have time to open the P2P platform ... @freeatnet Please help in solving this issue.

**Comment by KristinaPlusCoin** [comment] 2018-08-12 09:06
@freeatnet @Kryptoniq Hello friends! Can you please tell me when will the news on the PLCN coin listing?

**Comment by KristinaPlusCoin** [comment] 2018-08-13 07:25
@freeatnet "moved this from Needs Review to Information Complete in Add or Update Token **22 days ag**o"
Excuse me, we are very worried about our application. We really need to make a listing on your stock exchange ... We already appeared on DexDelta

**Comment by bobbypaintsstuf** [comment] 2018-08-13 13:36
https://github.com/therealMikkoK

**Comment by therealMikkoK** [comment] 2018-08-13 14:29
@bobbypaintsstuf soon... we will master this.

**Comment by bobbypaintsstuf** [comment] 2018-08-13 14:31
@therealMikkoK

**Comment by freeatnet** [comment] 2018-09-25 21:10
Resolved in #1726

**Closed by freeatnet** 2018-09-25 21:10 UTC
Labels: information complete, listing update
