### ISSUE TITLE
Listing Request - Ethereum Meta

### ISSUE THREAD

**Issue by ethermeta** [forkdelta/tokenbase#135] opened 2018-02-19 19:24 UTC
1. 0x56b6431f45d08eed55f34371386326c739eacbcc
2. https://ethermeta.com/
3. Ethereum Meta addresses a major weakness in Ethereum: the lack of privacy. Ethereum Meta enables smart contracts where no friend, family, nor foe can see what you bought or for how much. We are working on Smart Contract Mixer. After Ethereum platform implements Zero-Knowledge Snarks, we will add this feature to our system. Moreover, Ethereum Meta token is a foundation of the Anonymous E-Market Place that we are building to be accessible by Tor Browser and provide fully anonymous experience.
4. https://ethermeta.com/ (Wallet Section)
5. https://bitcointalk.org/index.php?topic=2659058.0

Thank you in advance!

Kindly,
Ethereum Meta Team

**Comment by Kryptoniq** [comment] 2018-02-22 17:14
Duplicate of #130.

**Closed** 2018-02-22 17:14 UTC
