### ISSUE TITLE
adding connect to the platform

### ISSUE THREAD

**Issue by Connecttoken** [forkdelta/tokenbase#1425] opened 2018-07-11 11:52 UTC
hi, could you please add CNCT to the main platform at the moment it is only avaliable throught contract address link.
0x54A9ed327F2614316914c3F3a782a77d0AA47AEe

**Comment by freeatnet** [comment] 2018-07-12 09:02
Duplicate of #1404.

**Closed by freeatnet** 2018-07-12 09:02 UTC
