### ISSUE TITLE
Industrial, academic, and experimental Non-ICO ERC-20 tokens bypassed and ignored

### ISSUE THREAD

**Issue by uniMgmt** [forkdelta/tokenbase#430] opened 2018-03-08 00:55 UTC
PLUM

This is Yet Another Request for listing with ForkDelta.  **The PLUM ERC-20 Token listed below is NOT an ICO, it is NOT an Airdrop, it is NOT an effort to sell, buy, or raise funds**.  The project is fully funded.  The reason for listing this ERC-20 token on ForkDelta.com is:
1.  Open market price discovery
2.  Token to ETH/USD mark-to-market
3.  Open source/results contribution(s) to the ETH community
4.  Intellectual experimentation

The contract address is 0x41104c8d51a80d9e2969dc23256a352de4b0ec33
ForkDelta.com raison d etre appears to be the ICO or Initial Coin Offering.  E.g. Raising funding for a concept or idea through the ERC 20 Token.  Our effort is different, in that we do not seek to raise any funding from investors.  PLUM SEEKS LISTING ONLY FOR PRICE DISCOVERY, IT IS NOT AN ICO.

After month(s), we grow frustrated having met the listed requirements repeatedly.

Contract address: 0x41104c8d51a80d9e2969dc23256a352de4b0ec33

Issuer's official website: www.42plums.com

Official contract address confirmation:

https://etherscan.io/token/0x41104c8d51a80d9e2969dc23256a352de4b0ec33

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2994051.0

Description:
This is primarily a research coin/tool/experiment at this point.  This ERC-20 Token is developed into a physical Hardware device for payment at locations without human(s).  Automated check-out, car-wash, laundromat, vending, toll booths and the like. Interesting parameters we wish to study are the free-market price discovery of the coin vs. tangible good(s) and services pricing and corresponding economic metrics.

We're trying to list an ERC-20 Token called PLUM for non-traditional/noble reasons.  ForkDelta seemed to be the most approachable exchange but we are now repeatedly frustrated.

**Comment by freeatnet** [comment] 2018-03-08 07:08
Duplicate of #78. Please add your information there.

**Closed by freeatnet** 2018-03-08 07:08 UTC

**Comment by uniMgmt** [comment] 2018-03-08 21:40
Done
