### ISSUE TITLE
Add Leadcoin Token

### ISSUE THREAD

**Issue by BitBit2** [forkdelta/tokenbase#1214] opened 2018-06-03 14:11 UTC
**Token address:**
0x5102791ca02fc3595398400bfe0e33d7b6c82267

**Issuer's official website:**
https://www.leadcoin.network/

**Description:** 

LeadCoin empowers businesses to sell their unused leads and buy hot leads with LDC from other businesses. 

**A link to the official contract address confirmation:** 

You will find the Smart Contract address here
https://blog.leadcoin.network/leadcoins-ldc-token-is-on-coinmarketcap.html

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/leadcoin

**Comment by freeatnet** [comment] 2018-06-06 12:27
Duplicate of #712.

**Closed by freeatnet** 2018-06-06 12:27 UTC
