### ISSUE TITLE
Delist Original Crypto Coin

### ISSUE THREAD

**Issue by OriginalFoundit** [forkdelta/tokenbase#2682] opened 2019-09-07 18:27 UTC
**What token should be updated?**
Original Crypto Coin 

0x0235fe624e044a05eed7a43e16e3083bc8a4287a
OCC

**What about the token should be updated?**
Please delist the token. We rebranded as TUSC and launched our own dedicated blockchain.

**Comment by freeatnet** [comment] 2019-09-11 18:37
Duplicate of #2610.

**Closed by freeatnet** 2019-09-11 18:37 UTC
