### ISSUE TITLE
Add Token: Walletours (WTS)

### ISSUE THREAD

**Issue by hernanWTS** [forkdelta/tokenbase#1329] opened 2018-06-20 20:21 UTC
**Token address:**
0x357af180d6822ebcdc269ea147cd3d36ed971596

**Issuer's official website:**
https://walletours.io

**Description:** 

The purpose of the WTS token is to allow the exchange of goods and services to the entire tourist community in the world.
We are working on the creation of a decentralized exchange.

**A link to the official contract address confirmation:** 

https://walletours.io
Click on the section: "Token", from the menu bar

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://youtu.be/nKmykrdTlNM
2. https://request.coinpulse.io/suggestions/6672/walletours-wts

**Comment by Kryptoniq** [comment] 2018-06-21 06:53
Duplicate of #1118

**Closed by Kryptoniq** 2018-06-21 06:53 UTC

**Comment by hernanWTS** [comment] 2018-06-21 14:46
Good Morning. I recently published two third-party links that discuss
Walletours.
Please, what would you verify?

Thank you very much

of #1118 <https://github.com/forkdelta/tokenbase/issues/1118>

https://github.com/forkdelta/tokenbase/issues/1118?_pjax=%23js-repo-pjax-container
