### ISSUE TITLE
Please list Dank Signals Token (DANK)

### ISSUE THREAD

**Issue by danksignals** [forkdelta/tokenbase#1143] opened 2018-05-23 21:33 UTC
This is a request to add a new token to tokenbase. 

**Token address:** 0xc354dde9ac078ed9572df94063c300d1d92468fd
Symbol ; DANK
decimals ;18
verifiable by logging into our website and selecting the withdrawal tab once logged into your account.
Verified on Etherscan
https://etherscan.io/token/0xc354dde9ac078ed9572df94063c300d1d92468fd
**Issuer's official website:** https://danksignals.club
also verifiable on our github profile here, https://github.com/danksignals/Dank-Signals-Token-Contract/blob/master/contract%20address

**Description:** DANK Signals is an intelligent ecosystem that solves the problems of trader interaction with cryptocurrency exchange. It is an intelligent and automatic solution, accessible for everyone, disregarding their experience, knowledge of financial analysis, and background. Using the system, traders learn the basics of crypto market as the information is divided into small bit courses, tutorials and strategy leasing to ensure that novice users fully understand all ins and outs of trading and investing safely. we also provide options to utilize artificial intelligencetrading bots for trading with ease on 4 major trading exchanges

**A link to the official contract address confirmation:** https://github.com/danksignals/Dank-Signals-Token-Contract/blob/master/contract%20address
This github profile is linked from our website https://danksignals.club in the header buttons, contract address saved in repo.

article - https://cryptovest.com/ico/dank-signals/
ico rating & review - https://icoranker.com/ico/dank-signals-traders-knowledge-hub/
ico rating & review  - https://www.trackico.io/ico/dank-signals/
press release - https://www.ccn.com/is-dank-signals-truly-the-most-important-upcoming-ico-project/
press release - https://www.businessnewser.com/2018/03/20/review-of-dank-signal-and-token-sales/
review- https://www.youtube.com/watch?v=ZYJp-MN75lc
review -  https://www.youtube.com/watch?v=lxBWYj4alGM

contact danksignals@gmail.com
telegram 
@danksignalsoliver
@danksignalschris

**Comment by danksignals** [comment] 2018-05-23 21:44
token sale completes on June 15th so would be rgeat if you could refrain from listing, until then.

**Comment by danksignals** [comment] 2018-06-03 19:18
Hi, I just updated token contract address. We had issue with verification of the first so had to relaunch. The contract in the original post is no verified on etherscan found here  - https://etherscan.io/token/0xc354dde9ac078ed9572df94063c300d1d92468fd

**Comment by freeatnet** [comment] 2018-06-06 12:45
Please keep the requests to a single issue. Duplicate of #1048.

**Closed by freeatnet** 2018-06-06 12:45 UTC
