### ISSUE TITLE
Listing of SURETY Token (SURE) on Tokenbase

### ISSUE THREAD

**Issue by NGUYENVQHUNG** [forkdelta/tokenbase#1648] opened 2018-09-06 09:42 UTC
Token address: 0x95382Ac82E886A367bAc9E1e23beAbe569bCfeD8

Issuer's official website: https://hearti.io/suretyai/

Description: Surety.AI platform  is  the  overall  ecosystem  that  Hearti  builds  to  spearhead  the  next generation  of  insurance  economy.  This  ecosystem,  which  will  include  new  crypto  token and  digital  wallet,  is  set  to  change  the  current  uninspired  and  value-deficient  uninsured and  unbanked  to  a  value-focused  insurance  system  that  will  stand  head  and  shoulders above traditional means.

A link to the official contract address confirmation:
https://etherscan.io/address/0x95382ac82e886a367bac9e1e23beabe569bcfed8#code

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://www.insurancebusinessmag.com/asia/features/interviews/turning-trials-into-technologyassisted-insurance-93225.aspx
2. https://www.straitstimes.com/business/have-a-hearti-chat-with-an-insurance-chatbot

**Comment by freeatnet** [comment] 2018-09-13 09:51
Duplicate of #1646. If you have additional information not mentioned in the original request, please post it as a comment on #1646.

**Closed by freeatnet** 2018-09-13 09:51 UTC
Labels: duplicate
