### ISSUE TITLE
Listing of CPPG Token

### ISSUE THREAD

**Issue by RanjoMc** [forkdelta/tokenbase#1321] opened 2018-06-18 09:07 UTC
**Token address:**
Contract Address: 0x345fD80105d95Fd8845d0E717B9590499b5756d0
Name: CPPG Token
Symbol: CPPG
Platform: ERC-20

**Issuer's official website:**
About Corss Platform Payment Gateway
Cross Platform Payment Gateway is product of Aeoliana Finance Pty Ltd, a 24 years old Australian company provides investment and mortgage loan services in Australia. Our registration details with Australian government as below:
Company Name: Aeoliana Finance Pty Ltd
Registered In: Feb 1993
ACN: 060 823 896
ABN: 83 060 823 896

Website: www.cppg.io
White Paper: http://www.cppg.io/CPPGToken-WhitePaper.pdf
Twitter: https://twitter.com/cppgtoken
Telegram: 

**Description:** 
Cross Platform Payment Gateway is coming up with advance payment gateway which supports transaction settlement for fiat as well as crypto currencies. Advantage of using Cross Platform Payment Gateways is merchant and customers can select own method of choice for payment gateway and if both method does not match Cross Platform Payment Gateway it will take care of conversion without charging extra fees unlike other payment gateway which collect exchange conversion fee for international transactions.
CPPG Tokens will be used as fuel to process transaction on Cross Platform Payment Gateway once system will be ready and moved to own blockchain.

**A link to the official contract address confirmation:** 
http://www.cppg.io/#tokenSale

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.reddit.com/user/Albert_Thomson_/comments/89qns3/free_cppg_tokens_distribution/
2. https://bitcointalk.org/index.php?topic=3232772.0

**Comment by RanjoMc** [comment] 2018-06-18 10:08
Telegram: https://t.me/CPPGToken
LinkedIn: https://www.linkedin.com/in/cppgtoken/

**Comment by umarjan9858** [comment] 2018-06-18 11:40
I must tell you CPPG is first payment gateway which accepts not only digital asset but also fiat currency .. And team CEO is 21 year experience so their exprience will definitely help...dont miss this oppurnity otherwise you will cry

**Comment by freeatnet** [comment] 2018-06-18 12:36
Duplicate of #1241.

**Closed by freeatnet** 2018-06-18 12:36 UTC
