### ISSUE TITLE
Request to list GoHelpFund Token (HELP)

### ISSUE THREAD

**Issue by batrinuvlad** [forkdelta/tokenbase#1141] opened 2018-05-23 12:29 UTC
Official website: https://gohelpfund.com

Description:

Humanitarian fundraising platform built in order to provide transparency for donations and to attract new supporters in the fundraising ecosystem. The token will be used as the main currency of the platform. Users can donate via other cryptocurrency or FIAT, which will be converted to HELP token.

Blockchain will be used in our donation system in order to provide transparency. Users will know where the money goes and they will be motivated to donate for humanitarian causes, having confidence that the money will not end up in the wrong hands.

We will also migrate to our own blockchain solution, but for now we're using the Ethereum net.

How will the token be used?
The token will be used as the main currency of the platform. Users can donate via other cryptocurrency or FIAT, which will be converted to HELP token.

Official contract address confirmation: https://tokensale.gohelpfund.com/home -> Token Tracker section in the top area.

Contract address: 
https://etherscan.io/token/0xbbc2045d335cb224228f1850b29173d9d7d7b989#readContract

Important press releases:

1. https://cointelegraph.com/news/romanian-startup-targets-400-bln-charity-fundraising-market-with-new-platform
2. https://themerkle.com/go-help-fund-connecting-people-with-blockchain-technology/
3. https://icomarks.com/ico/gohelpfund
4. https://icoholder.com/en/gohelpfund-17275
5. http://bitcoinist.com/go-help-fund-making-world-better-place-live/

**Comment by freeatnet** [comment] 2018-06-06 12:48
Closing as duplicate of #1111. If you have additional information related to the token, please post it as a comment on #1111.

**Closed by freeatnet** 2018-06-06 12:48 UTC
